services:
    sourceability.console_toolbar.console.profiler_toolbar_renderer:
        class: 'Sourceability\ConsoleToolbarBundle\Console\ProfilerToolbarRenderer'
        public: true # For behat extension DI
        arguments:
            $router: '@router'
            $profiler: '@?profiler'
            $twig: '@twig'
            $templates: '%data_collector.templates%'
            $hiddenPanels: [] # Replaced by DI Extension
            $maxColumnWidth: 30  # Replaced by DI Extension

    sourceability.console_toolbar.profiler.recent_profile_loader:
        class: 'Sourceability\ConsoleToolbarBundle\Profiler\RecentProfileLoader'
        public: true # For behat extension DI
        arguments:
            $profiler: '@?profiler'

    sourceability.console_toolbar.event_listener.console_toolbar_listener:
        class: 'Sourceability\ConsoleToolbarBundle\EventListener\ConsoleToolbarListener'
        arguments:
            $toolbarRenderer: '@sourceability.console_toolbar.console.profiler_toolbar_renderer'
            $recentProfileLoader: '@sourceability.console_toolbar.profiler.recent_profile_loader'
            $kernel: '@kernel'
        tags:
            - { name: 'kernel.event_subscriber' }
