services:
    Sourceability\ConsoleToolbarBundle\Console\ProfilerToolbarRenderer:
        class: Sourceability\ConsoleToolbarBundle\Console\ProfilerToolbarRenderer
        public: true # For behat extension DI
        arguments:
            $router: '@router'
            $profiler: '@?profiler'
            $twig: '@twig'
            $templates: '%data_collector.templates%'
            $hiddenPanels: [] # Replaced by DI Extension
            $maxColumnWidth: 30  # Replaced by DI Extension

    Sourceability\ConsoleToolbarBundle\Profiler\RecentProfileLoader:
        class: Sourceability\ConsoleToolbarBundle\Profiler\RecentProfileLoader
        public: true # For behat extension DI
        arguments:
            $profiler: '@?profiler'

    Sourceability\ConsoleToolbarBundle\EventListener\ConsoleToolbarListener:
        class: Sourceability\ConsoleToolbarBundle\EventListener\ConsoleToolbarListener
        arguments:
            $toolbarRenderer: '@Sourceability\ConsoleToolbarBundle\Console\ProfilerToolbarRenderer'
            $recentProfileLoader: '@Sourceability\ConsoleToolbarBundle\Profiler\RecentProfileLoader'
            $kernel: '@kernel'
        tags:
            - { name: 'kernel.event_subscriber' }
